spring:
  datasource:
    url: jdbc:h2:mem:diorest
    username: diorest
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      dll-auto: create # validade | update | create | create-drop
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
